//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADREW_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Departments = new HashSet<Department>();
            this.Employees = new HashSet<Employee>();
            this.Projects = new HashSet<Project>();
            this.DepartmentPositions = new HashSet<DepartmentPosition>();
            this.ProjectPositions = new HashSet<ProjectPosition>();
        }
    
        public int TaskID { get; set; }
        public string Name { get; set; }
        public string Descr { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public bool IsMilestone { get; set; }
    
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<DepartmentPosition> DepartmentPositions { get; set; }
        public virtual ICollection<ProjectPosition> ProjectPositions { get; set; }
    }
}
